[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.deps]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-left]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "alchemist-left",
    "--",
    "-O",
    "ihex",
    "alchemist-left.hex",
]

[tasks.objcopy-right]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "alchemist-right",
    "--",
    "-O",
    "ihex",
    "alchemist-right.hex",
]

[tasks.uf2-left]
command = "python"
args = [
    "scripts/uf2conv.py",
    "alchemist-left.hex",
    "-c",
    "-f",
    "0xe48bff56",                  # Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "alchemist-left.uf2",
]
dependencies = ["objcopy-left"]

[tasks.uf2-right]
command = "python"
args = [
    "scripts/uf2conv.py",
    "alchemist-right.hex",
    "-c",
    "-f",
    "0xe48bff56",                  # Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "alchemist-right.uf2",
]
dependencies = ["objcopy-right"]

[tasks.uf2]
dependencies = ["uf2-right", "uf2-left"]
