[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }

[tasks.deps]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "alchemist",
    "--",
    "-O",
    "ihex",
    "alchemist.hex",
]

[tasks.uf2]
command = "python"
args = [
    "scripts/uf2conv.py",
    "alchemist.hex",
    "-c",
    "-f",
    "0xe48bff56",                  # Use your chip family ID in the uf2conv.py file as -f argument
    "-o",
    "alchemist.uf2",
]
dependencies = ["objcopy"]
